### ISSUE TITLE
Not sure how to include ABLLINK

### ISSUE THREAD

**Issue by songproducer** [AudioKit/AudioKitSynthOne#101]
Hi,

I tried putting the LinkKit folder in the AudioKitSynthOne folder but I get

> /Users/leotreasure/AudioKitSynthOne/AudioKitSynthOne/DSP/AudioKitSynthOne-Bridging-Header.h:19:11: 'ABLLink.h' file not found
> 
> <unknown>:0: error: failed to emit precompiled header '/Users/leotreasure/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-dmeevmcoabjtdfegbnebbtdojzqw/Build/Intermediates.noindex/PrecompiledHeaders/AudioKitSynthOne-Bridging-Header-swift_1P4WBBS69SZJL-clang_1S74ORPBXNQDJ.pch' for bridging header '/Users/leotreasure/AudioKitSynthOne/AudioKitSynthOne/DSP/AudioKitSynthOne-Bridging-Header.h'

**Comment by aure** [comment]
Did you drag it into the Xcode project or just put it into the folder on the file system?  it should look like this in Xcode: 

![image](https://user-images.githubusercontent.com/13122/62760930-1d107c80-ba3a-11e9-870c-54c9b98bbedf.png)

Feel free to reopen this issue if you provide more information on how you're including the file.
