### ISSUE TITLE
iPhone: how to close the bluetooth midi modal?

### ISSUE THREAD

**Issue by guaka** [AudioKit/AudioKitSynthOne#102]
On iPhone: how to close the bluetooth midi modal?

I can't get away from this modal window:
![image](https://user-images.githubusercontent.com/54728/63164463-cf42d800-c028-11e9-81a0-1bc5a5d3e14c.png)

**Comment by sieren** [comment]
Hey.. unfortunately some code had snucked in that turned "Done" button is white.. you can see it on the top right if you look closely. We've just fixed it in https://github.com/AudioKit/AudioKitSynthOne/pull/103 and it should be in the next update. Thanks for reporting this! :)
