### ISSUE TITLE
Here is a TDD style "issue": The app isn't built for running on macOS yet (click that checkbox) and isn't routing audio and midi to and from macOS DAWS "yet". 

### ISSUE THREAD

**Issue by 01GOD** [AudioKit/AudioKitSynthOne#111]
Here is a TDD style "issue": The app isn't built for running on macOS yet (click that checkbox) and isn't routing audio and midi to and from macOS DAWS "yet". 

Thanks in advance for getting that functioning this month and thank Me later for inspiring a new type of software synth standard and possibly also a new DAW.

**Comment by analogcode** [comment]
Synth One for Mac is coming soon.
