### ISSUE TITLE
Xcode 11.1 complie error

### ISSUE THREAD

**Issue by tommyyoon** [AudioKit/AudioKitSynthOne#112]
I am getting:
module compiled with Swift 5.0 cannot be imported by the Swift 5.1 compiler: /.../AudioKitSynthOne-master/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64.swiftmodule

Is there fix or workaround? Thanks.

**Comment by aure** [comment]
Are you using AudioKit 4.9? try doing a pod update

**Comment by tommyyoon** [comment]
I changed it to 4.9 and I am able to compile. Thanks!
