### ISSUE TITLE
Crash on start-up

### ISSUE THREAD

**Issue by extreamsd** [AudioKit/AudioKitSynthOne#123]
I downloaded AudioKitSynthOne from GitHub, did the pod commands, changed the bundle identifiers and built the project using Xcode 11.2. On start-up (does not matter if I take the master or develop branch), it crashes with an uncaught NSException on :

window?.makeKeyAndVisible()

Stack trace:
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001bfc8a9c0 in objc_exception_throw ()
#1	0x00000001c09bbbc0 in +[NSException raise:format:] ()
#2	0x00000001cb150de8 in UINibDecoderDecodeObjectForValue ()
#3	0x00000001cb15116c in UINibDecoderDecodeObjectForValue ()
#4	0x00000001cb0f0304 in -[UINibDecoder decodeObjectForKey:] ()
#5	0x00000001ed328e70 in -[UIView initWithCoder:] ()
#6	0x00000001ed2d72e8 in -[UIScrollView initWithCoder:] ()
#7	0x00000001ed1e0d6c in -[UITextView initWithCoder:] ()
#8	0x00000001cb150f28 in UINibDecoderDecodeObjectForValue ()
#9	0x00000001cb0f0304 in -[UINibDecoder decodeObjectForKey:] ()
#10	0x00000001ecb7c508 in -[UIRuntimeConnection initWithCoder:] ()
#11	0x00000001cb150f28 in UINibDecoderDecodeObjectForValue ()
#12	0x00000001cb15116c in UINibDecoderDecodeObjectForValue ()
#13	0x00000001cb0f0304 in -[UINibDecoder decodeObjectForKey:] ()
#14	0x00000001ecb79df0 in -[UINib instantiateWithOwner:options:] ()
#15	0x00000001ec91526c in -[UIViewController _loadViewFromNibNamed:bundle:] ()
#16	0x00000001ec915c14 in -[UIViewController loadView] ()
#17	0x00000001ec915ed8 in -[UIViewController loadViewIfRequired] ()
#18	0x00000001ec916628 in -[UIViewController view] ()
#19	0x00000001ed04ab10 in __67-[UIStoryboardEmbedSegueTemplate newDefaultPerformHandlerForSegue:]_block_invoke ()
#20	0x00000001ed04cc38 in -[UIStoryboardSegueTemplate _performWithDestinationViewController:sender:] ()
#21	0x00000001ed04cae4 in -[UIStoryboardSegueTemplate _perform:] ()
#22	0x00000001ed04cdb0 in -[UIStoryboardSegueTemplate perform:] ()
#23	0x00000001ec91607c in -[UIViewController loadViewIfRequired] ()
#24	0x00000001ec916628 in -[UIViewController view] ()
#25	0x00000001ecef4e64 in -[UIWindow addRootViewControllerViewIfPossible] ()
#26	0x00000001ecef540c in -[UIWindow _setHidden:forced:] ()
#27	0x00000001ecf05ce8 in -[UIWindow makeKeyAndVisible] ()
#28	0x0000000100aef6e0 in AppDelegate.application(_:didFinishLaunchingWithOptions:) at /Users/dwr/Downloads/AudioKitSynthOne-develop/AudioKitSynthOne/AppDelegate.swift:49

When I browse around the stack trace, I see a lot of 'cloud' related texts like CloudDocsLibrary. Not sure what to do next. I managed to build SynthOne in February of this year.

Some new info: it says:
[<AudioKitSynthOne.KeyboardView 0x104822cf0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key darkMode.

**Comment by aure** [comment]
Is this still happening? Sorry no one responded to this issue. Since its so old I'll close it for now, but feel free to update with more info.
