### ISSUE TITLE
GarageBand. 

### ISSUE THREAD

**Issue by henne2k** [AudioKit/AudioKitSynthOne#151]
When I connect synthone to Garage Band it’s a little inconvenient to record sounds. In apps like Model D minimiog there is a mini control panel that’s very helpful. Could you implement that or is that planed?

**Comment by roberChen** [comment]
I have downloaded AudioKitOne for a long time, it's a nice program but I really hope that it'll support AU3 to work better with Garageband.

**Comment by aure** [comment]
Yeah, some of the updates in AudioKit to make AUv3s will eventually make their way here.
