### ISSUE TITLE
Code can't compile on Xcode 11.5

### ISSUE THREAD

**Issue by Zieng** [AudioKit/AudioKitSynthOne#162]
Hi I'm not expert on iOS develop so please bear me if I asked stupid question.

I cloned the code, follow the readme and try to compile the project, and unfortunately it can't compile.

The build failed with reason:
```
module compiled with Swift 5.1.1 cannot be imported by the Swift 5.2.4 compiler: /Users/$USER/code/AudioKitSynthOne/Pods/AudioKit/iOS/AudioKit.framework/Modules/AudioKit.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```
Full error log:

> CompileSwift normal x86_64 /Users/$USER/code/AudioKitSynthOne/OneSignalNotificationServiceExtension/NotificationService.swift (in target 'OneSignalNotificationServiceExtension' from project 'AudioKitSynthOne')
    cd /Users/$USER/code/AudioKitSynthOne
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/$USER/code/AudioKitSynthOne/OneSignalNotificationServiceExtension/NotificationService.swift -emit-module-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService\~partial.swiftmodule -emit-module-doc-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService\~partial.swiftdoc -emit-module-source-info-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService\~partial.swiftsourceinfo -serialize-diagnostics-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService.dia -emit-dependencies-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService.d -emit-reference-dependencies-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService.swiftdeps -target x86_64-apple-ios11.3-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk -I /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator -F /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator -F /Users/$USER/code/AudioKitSynthOne/Pods/AudioKit/iOS -F /Users/$USER/code/AudioKitSynthOne/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -application-extension -enable-testing -g -module-cache-path /Users/$USER/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -D ABLETON_ENABLED_0 -serialize-debugging-options -Xcc -working-directory -Xcc /Users/$USER/code/AudioKitSynthOne -enable-anonymous-context-mangled-names -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-generated-files.hmap -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-own-target-headers.hmap -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-all-target-headers.hmap -Xcc -iquote -Xcc /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-project-headers.hmap -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/$USER/code/AudioKitSynthOne -Xcc -I/Users/$USER/code/AudioKitSynthOne -Xcc -I/Users/$USER/code/AudioKitSynthOne/Pods/Headers/Public -Xcc -I/Users/$USER/code/AudioKitSynthOne/Pods/Headers/Public/Audiobus -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/DerivedSources-normal/x86_64 -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/DerivedSources/x86_64 -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DABLETON_ENABLED=0 -Xcc -DCOCOAPODS=1 -import-objc-header /Users/$USER/code/AudioKitSynthOne/AudioKitSynthOne/DSP/AudioKitSynthOne-Bridging-Header.h -pch-output-dir /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/PrecompiledHeaders -pch-disable-validation -parse-as-library -module-name OneSignalNotificationServiceExtension -o /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/NotificationService.o -index-store-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Index/DataStore -index-system-modules

After some googling, one [answer](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler) told me we should set `BUILD_LIBRARY_FOR_DISTRIBUTION = YES;` so I did so, but I started to get another build error:
```
error: using bridging headers with module interfaces is unsupported
```
Full error log:

> CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'OneSignalNotificationServiceExtension' from project 'AudioKitSynthOne')
    cd /Users/$USER/code/AudioKitSynthOne
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name OneSignalNotificationServiceExtension -Onone -enable-batch-mode -enforce-exclusivity=checked @/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension.SwiftFileList -DDEBUG -DABLETON_ENABLED_0 -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk -target x86_64-apple-ios11.3-simulator -g -module-cache-path /Users/$USER/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -application-extension -enable-testing -index-store-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Index/DataStore -enable-library-evolution -swift-version 5 -I /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator -F /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator -F /Users/$USER/code/AudioKitSynthOne/Pods/AudioKit/iOS -F /Users/$USER/code/AudioKitSynthOne/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -parse-as-library -c -j8 -output-file-map /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension.swiftmodule -emit-module-interface-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension.swiftinterface -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-generated-files.hmap -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-own-target-headers.hmap -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-all-target-headers.hmap -Xcc -iquote -Xcc /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension-project-headers.hmap -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/$USER/code/AudioKitSynthOne -Xcc -I/Users/$USER/code/AudioKitSynthOne -Xcc -I/Users/$USER/code/AudioKitSynthOne/Pods/Headers/Public -Xcc -I/Users/$USER/code/AudioKitSynthOne/Pods/Headers/Public/Audiobus -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/DerivedSources-normal/x86_64 -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/DerivedSources/x86_64 -Xcc -I/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -DABLETON_ENABLED=0 -Xcc -DCOCOAPODS=1 -emit-objc-header -emit-objc-header-path /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension-Swift.h -import-objc-header /Users/$USER/code/AudioKitSynthOne/AudioKitSynthOne/DSP/AudioKitSynthOne-Bridging-Header.h -pch-output-dir /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/PrecompiledHeaders -working-directory /Users/$USER/code/AudioKitSynthOne

My environment:
```
macOS: 10.15.5 (19F101)
Xcode: 11.5 (11E608c)
commit: 86f3e1d6296c9008f6a5cc101fd8749916d30c2e
```

**Comment by dogehk** [comment]
You must be updated AudioKit version on the pod file.
I solved using 4.10.1 version of AudioKit.

**Comment by Zieng** [comment]
Hi @dogehk thanks for your reply!
I tried to use the 4.10.1 version of AudioKit:
```
diff --git a/Podfile b/Podfile
index 514ebad0..e889fd85 100644
--- a/Podfile
+++ b/Podfile
@@ -8,7 +8,7 @@ source 'https://github.com/CocoaPods/Specs.git'

 def available_pods
     pod 'AppCenter'
-    pod 'AudioKit', '= 4.9.2'
+    pod 'AudioKit', '= 4.10.1'
     pod 'Disk', '~> 0.3.2'
     pod 'Audiobus'
     pod 'OneSignal', '>= 2.6.2', '< 3.0'
@@ -20,7 +20,7 @@ end

 target 'OneSignalNotificationServiceExtension' do
     pod 'OneSignal', '>= 2.6.2', '< 3.0'
-    pod 'AudioKit', '= 4.9.2'
+    pod 'AudioKit', '= 4.10.1'
 end
```
but I still can get it compiled. There are new errors coming:
```
 framework not found Pods_OneSignalNotificationServiceExtension
```
Full error log:

> Ld /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension normal x86_64 (in target 'OneSignalNotificationServiceExtension' from project 'AudioKitSynthOne')
    cd /Users/$USER/code/AudioKitSynthOne
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios11.3-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk -L/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -F/Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator -F/Users/$USER/code/AudioKitSynthOne/Pods/AudioKit/iOS -F/Users/$USER/code/AudioKitSynthOne/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework -filelist /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension.swiftmodule -lstdc++ -ObjC -lc++ -framework AVFoundation -framework AudioKit -framework AudioKitUI -framework CoreGraphics -framework OneSignal -framework SystemConfiguration -framework UIKit -framework UserNotifications -framework WebKit -e _NSExtensionMain -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/OneSignalNotificationServiceExtension.appex-Simulated.xcent -framework Pods_OneSignalNotificationServiceExtension -Xlinker -dependency_info -Xlinker /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Intermediates.noindex/AudioKitSynthOne.build/Debug-iphonesimulator/OneSignalNotificationServiceExtension.build/Objects-normal/x86_64/OneSignalNotificationServiceExtension_dependency_info.dat -o /Users/$USER/Library/Developer/Xcode/DerivedData/AudioKitSynthOne-fwbpfaeosrpufkeapdpxwwfrfyha/Build/Products/Debug-iphonesimulator/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension

Any more suggestions?

**Comment by Zieng** [comment]
OK, I finally made it compile.

1. use AudioKit version 4.10.1 as @dogehk suggested
2. open AudioKitSynthOne.xcworkspace instead of AudioKitSynthOne.xcodeproj
3. fix the `AudioKitSynthOne/AudioKitSynthOne/DSP/AKSynthOne.swift:12:2: Explicit '@objc' on subclass of 'AKPolyphonicNode' requires iOS 13.0.0` error

**Comment by dogehk** [comment]
@Zieng  Great!

**Comment by marcussatellite** [comment]
@Zieng @dogehk I submitted a PR with these changes....I tested with Xcode 11.5 and iOS13.5.  I'm asking a team member with access to devices running iOS < 13 to test as part of the PR review.  Thank you for debugging this.

**Comment by marcussatellite** [comment]
@Zieng this is my PR with your fixes:
https://github.com/AudioKit/AudioKitSynthOne/pull/163

**Comment by marcussatellite** [comment]
@Zieng if the testing goes well...I can cancel my PR and you can submit instead if you want...really appreciate your effort and want you to be credited with it.

**Comment by Zieng** [comment]
@marcussatellite Thanks for your quick response! 

It seems the Travis CI build failed on xcode11.2 and I'm not sure if I can help debug the build failures because I'm kind new to iOS development and I only have xcode 11.5 installed.
This is a great project and I'm wiling to help so if there is something I can help please let me know.

Cheers

**Comment by marcussatellite** [comment]
Yeah, devices with iOS versions less than 13 are getting a build error, with this PR.  Will share updates in the #synthone AudioKit Slack channel.
