### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by manowargoblin** [AudioKit/AudioKitSynthOne#2]
Master & also auv3(once I added your AB3 key)
Conductor.swift:start():118:Logging is ON
Conductor.swift:start():145:AudioKit Started
libc++abi.dylib: terminating with uncaught exception of type NSException

this is in AppDelegate.swift.

app runs up,  I can see the main UI, but I get the above issue after a few seconds...

Using your bundle name & AB key. Copied the Pods.xcodeproj into project(seems to be the best way to get it linked). I've turned off cloud & notifications in the app.

**Comment by manowargoblin** [comment]
ok. Its seems this is related to presets (or maybe lack of?) 
I noticed the AUv3 & the Master both say ....Loading... in the header. If I wait or press any header button I get something like this:

AKS1Extension    17:53:32.250286 +0100    -[AKS1Extension.HeaderViewController nextPresetPressed:]: unrecognized selector sent to instance 0x101f0b4d0
AKS1Extension    17:53:32.252631 +0100    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AKS1Extension.HeaderViewController nextPresetPressed:]: unrecognized selector sent to instance 0x101f0b4d0'

**Comment by analogcode** [comment]
Presets are included. This is the full source code. 

There is no need to add pods.xcodeproj or manipulate the project in any way to run it. 

Simply clone and run “pod install”

**Comment by aure** [comment]
Looks like your issues have to do with AUv3/AKS1Extension.  This is not a supported problem since it is  under development.

**Comment by manowargoblin** [comment]
Hi Matt,

  I wasn't checking the devices/console properly. It was failing on the mailChimp ID (probably the pop up for free presets needs it) so did a clean install and it now works fine.


  Will checkout the auv3 version too.


  Regards

Tony





________________________________

**Comment by analogcode** [comment]
@manowargoblin 
Thanks for the reminder about the MailChimp Key. I've added a check to the code to skip the mailing list signup in the case of a removed MailChimp key. Hopefully that will make it easier for people exploring the code.
