### ISSUE TITLE
iOS power consumption analysis required

### ISSUE THREAD

**Issue by cogito-clarus** [AudioKit/AudioKitSynthOne#29]
![45763219-dd83-4692-a2e8-ee440ef2a4d2](https://user-images.githubusercontent.com/20665220/48927680-eb548700-eea5-11e8-99e7-a79d2eb74424.jpeg)

It would seem that a CPU might be spinning waiting for soft key input or MIDI events.  I’d love to solve this, but i’m an iOS development amateur.

**Comment by marcussatellite** [comment]
I would need more information to determine if 42% was an unreasonable amount or not.

When I was writing the dsp: whenever I had a choice between higher quality and lower battery I always chose higher quality.

**Comment by cogito-clarus** [comment]
i would agree 100% with you since it's an audio app - except the battery won't charge on a 87W power supply with the app *not* being actively played/no current focus...there has to be a balance...like if the app is not in the foreground, it goes to power saving mode.  As i indicated, the MPC Pro 2 is in the background and not even showing up.  I'm coming from a java/scala/python/c background and am just starting to learn (and hate) swift through the udemy course, so i'm not yet qualified to understand the event model and how to implement a hibernate mode.  But i will look into this as my skills improve.

**Comment by marcussatellite** [comment]
You have some power-conservation options in settings:
![aks1_power_conservation](https://user-images.githubusercontent.com/16432863/48952685-e3bdce00-eef7-11e8-8ef2-30862a21297b.jpg)
