### ISSUE TITLE
Crashes on iPad mini 4

### ISSUE THREAD

**Issue by rcarmo** [AudioKit/AudioKitSynthOne#31]
The Mini 4 is a bit long in the tooth, I know, but It can still run the latest iOS, and SynthOne crashes after a few seconds of playing on most patches (no discernible pattern).

**Comment by aure** [comment]
Sorry it has taken a while to respond.  With recent developments, we're working on some optimization that may help with this.  Stay tuned. For now there's not much we can directly to address this issue, so I'll close it.
