### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by Wiksnet** [AudioKit/AudioKitSynthOne#38]
Tested on iPad Pro 13 inch - CPU usage is about 30-45% in idle. And a lot more in the old iPads
Sound of AUv3 in 90% cases is late and goes crazy (I used code for auv3 from brokenV3) If I add two or more plugins, then CPU load 100%  and sound is hang

**Comment by aure** [comment]
Hi Wiksnet.  Yea, its in a broken branch for a reason. :).  What is your testing method.  What host?  How do the numbers in AUv3 compare with the standalone app? Lets use this issue for further communication, but since this is on-going develop, I'll close this as an open issue.

**Comment by Wiksnet** [comment]
Hello Aure,
I use **Garageband** and **Cubasis 2**. iPad 12.9inch, ios: 12.1.3 (16D40). Output: built-in iPad speakers.

1) First I compiled app (no difference if I run debug+garageband or just compile app and run garageband)
2) Open GarageBand or Cubasis (better garageband, in cubasis for some reason in 50% of cases it worked fine)
3) Remove all instruments and add just one Synth One auv3 

> result... **sound is fine, but CPU in the XCode or Cubasis metric control is about 32-45%** _that seems to be alarming, because the simple use of SynthKit with 1 oscillator usually shows 1% CPU, other auv3 plugins also shows for me 1-5% cpu_

4) Add second auv3:Synth One instrument

> the sound starts to distort very much and the processor shows 75-100% load
it seems as if two synthesizers use one buffer for sound and edit it - but I'm newbie for programming with audio and can't be sure.  one thing I am sure for sure. that this should not be so, because adding 4-5 synthesizers just puts down the whole system and GarageBand or Cubasis is hang.

ps...
I tried to record a video today, but for the most cases it worked all day for me :) Only 3-4 times I noticed it. Yesterday it not worked at all in 90% cases. Anyway I'll try to catch it and show you. 
Also I went the other way and created an empty new project with added AudioKit framework. Auv3 is running and by pressing a note I just reproduce sound of 1 oscillator using this code:
` //osc
                                        let oscillator = AKOscillator()    //Create the sound generator
                                        
                                        
                                        //master out
                                        AudioKit.output = oscillator    //Tell AudioKit what to output
                                        
                                        do {
                                            try AudioKit.start()    ///Start up AudioKit
                                        } catch {
                                            print(error)
                                        }
                                        
                                        oscillator.amplitude = 0.5
                                        oscillator.frequency = random(in: 220...880)    //Set oscillator parameters
                                        oscillator.start()    //Start the oscillator`

It sound good in garageband/cubasis and cpu:0-1%, but when I'm adding a second auv3, then sound  then the sound is very distorted. 

Here is private video - https://youtu.be/SDG_x2yAM9E

and also issue with cpu load (this one from "broken" branch*, but for the master cpu load is actually same)
https://studio.youtube.com/video/8OMlE80o9DM/edit

**Comment by Wiksnet** [comment]
Finally catch it - https://www.youtube.com/watch?v=vdrDd3WEmVo

**Comment by aure** [comment]
Yikes, we definitely got some issues don't we?  I'll see what I can do.  I think I see what is wrong with your experiment, I'll make a commit there directly.

**Comment by Wiksnet** [comment]
Thanks. Sure. I rather ran into two problems. **1st** is a broken/hang sound like on the last video (used code from "broken" branch, nothing has been changed). **And the second** is that the sound from plugin1 comes out from a  second pluging too. Even if I did not press the note on second. - The same issue actually I saw in the "experimentation" branch.
