### ISSUE TITLE
Optimize layout for new iPad Pros

### ISSUE THREAD

**Issue by wesdelp** [AudioKit/AudioKitSynthOne#52]
Seen below, the new 2018 iPad Pros introduced new screen sizes which changed the ratios, causing some **major** black borders (especially on the 11”)

[Here](
https://link.medium.com/vZmCiBaVQU) is a pretty in-depth post of how Auto Layout reacts to those changes.

Depending on how SynthOne is laid out, it sounds like it could be as simple as adding new LaunchImages, or, potentially a much more involved rewrite of the layout.

I’m willing to mess around with it, but, not having much experience in iOS, an issue sounded like a better place to start :)

![7916ddd3-6a17-4dec-b288-df360f245b66](https://user-images.githubusercontent.com/6852648/53929928-732d5e00-405d-11e9-9d1d-4efe26c05a3c.png)

**Comment by analogcode** [comment]
It's non-trivial and would require a custom re-working of every single storyboard and layout. And, of course, new custom UI design's for each additional layout to make use of that extra space specifically for each iPad size. 

A decision was made to use the same layout on every iPad.

**Comment by wesdelp** [comment]
I had a feeling that might be the case. Thanks for clarifying.
