### ISSUE TITLE
Add iPhone App

### ISSUE THREAD

**Issue by BenKesselring** [AudioKit/AudioKitSynthOne#9]
How feasible would this be? Synth One looks _amazing_, but there are plenty of us (dozens, I say!) who use our iPhones for music and don't have iPads for varying reasons.

**Comment by analogcode** [comment]
@BenKesselring - Luckily, the code runs on an iPhone now. It's a matter of a volunteer stepping up to create and maintain a UI interface for the iPhone. 

Anyone reading this want to volunteer? :) 

matthew@audiokitpro.com

**Comment by analogcode** [comment]
![2018-08-18 19 03 49](https://user-images.githubusercontent.com/2042313/44310145-6c7c1980-a39f-11e8-83bc-5ce9006d758f.jpg)

The UI fits nicely on Plus size phones, at least.

**Comment by BenKesselring** [comment]
That's great to know! I may have to build for iPhone X and see how it scales. If the UI mostly needs just minor tweaking, I might take a stab at it.

**Comment by brucedaniel** [comment]
I'm pondering working on the ios port for this. Is there any design work done as far as speccing what iphone layout should look like? I don't feel like I understand the featureset enough to know how stuff should scale, but I'm pretty fast as UI if anyone has already figured out the layout.

**Comment by Ichicoro** [comment]
Any update on this issue? Is there any way an inexperienced swift dev can help?

**Comment by analogcode** [comment]
Hey everyone, I'm going to take the lead on this. I should have a (mostly) working branch pushed by next week. Here's a quick preview of my progress: https://twitter.com/AudioKitPro/status/1079894842270871552

**Comment by analogcode** [comment]
This is done! 
https://audiokitpro.com/synth-one-for-iphone-released/
